### ISSUE TITLE
python requests kullanma

### ISSUE THREAD

**Issue by serensoner** [atakandemirkir/php-thodex-api#1]
merhaba,

python requests library'sini kullandigim zaman, header'a eger 

`'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0',
`

eklemezsem cloudflare redirect ediyor, haliyle yanit alamiyorum. eger kullanirsam da, post request'lerde 

` {'error': {'code': 610, 'message': 'The selected Authorization is invalid.'}, 'result': None}
`

cevabi donuyor. bir fikriniz var mi acaba niye?

**Comment by atakandemirkir** [comment]
Merhaba,

1. si cloudflare ile alakalı user agent kullanmadığınız için veya default user agent cloud flare kontrollerinden geçmediği için. bu yönlendirme normal normal.

2. si header a bilgi eklemediğiniz için veya yanlış eklendiği için doğrulamayı yapamıyor.
            Header' a Authorization bilgisi eklemeniz lazım. Aşağıdaki gibi göndericeğiniz parametreleri key değerlerine göre sıralayıp aldığınız hash değerini header a Authorization olarak eklemeniz lazım. Aşağıda aynı işlemin php versiyonunu bulabilirsiniz. _encode fonksiyonunu python için ayarlayıp header a ekleyebilirsiniz. 

`
    $authorization = $this->_encode($request->params);
    $headers[] = 'Authorization: ' . $authorization;

    private function _encode($params) {
        ksort($params);
        $params['secret'] = $this->api_secret;
        return hash('sha256', http_build_query($params));
    }

`
Yakında https://github.com/thodex-exchange hesabında python içinde bu tarz bir repo yazılacak diye biliyorum. Bur repoyuda oraya ekleyeceğiz.

İyi çalışmalar.

**Comment by serensoner** [comment]
Hizli donus icin tesekkurler. authorization'a ayni zamanda post parametrelerini gondermek gerektigini atlamisim. Oyle yapinca hemen cozuldu. Iyi calismalar.

Bu arada alakasiz bir yer olacak ama sorayim; yakin gelecektewithdraw ve deposit history fonksiyonlarina API erisimi acmayi planliyor musunuz?

**Comment by atakandemirkir** [comment]
Merhaba,

O konuda ben birşey diyemem destek bölümünden yazarsanız değerlendirmeye alırlar.

İyi çalışmalar.
